apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test-database-cluster
  namespace: api
  labels:
    app: api-test-database-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-test-database-cluster
  template:
    metadata:
      labels:
        app: api-test-database-cluster
    spec:
      containers:
      - name: api-test-database-cluster
        image: railnlays/api-test-database-cluster:latest
        ports:
        - containerPort: 5000
        env:
        - name: WORKERS
          value: "1"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /healthzReadiness
            port: 5000
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthzLiveness
            port: 5000
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /healthzStartup
            port: 5000
          failureThreshold: 10
          periodSeconds: 5